### PR TITLE
Added Myself

### PR DESCRIPTION
**Pull request by whoadnan101**
Just added myself to the contributors list, Hope you will merge it.
Thank You!

### CODE REVIEW

**Comment by wbhoomika** [comment]
Hey let's start by getting a basic structure ready.

**Comment by whoadnan101** [comment]
what am i supposed to do here?
create a basic webpage? or something like that

**Comment by wbhoomika** [comment]
yes that would be good to start with, just have a page with header. I will try to create some tasks.

**Comment by whoadnan101** [comment]
Just proposed a simple hover social media icons webpage hope you like and will merge it.
Thank you!

**Comment by Squirrelthug** [comment]
I added some SEO meta tags and a scroll to top button that shows up when you scroll to the bottom. Gotta add content to make it long enough to scroll but when you do it's there.

**Review by wbhoomika — APPROVED** [review]

**Pull request merged**
